runtime: python37

handlers:

- url: /static
  static_dir: static

- url: /images
  static_dir: static/images

- url: /fonts
  static_dir: static/fonts

- url: /js
  static_dir: static/js

- url: /css
  static_dir: static/css

- url: .*
  script: auto
  secure: always
